domain_path: /home/tartanauv/TAUV-Acoustics/hdl/projects/som_platform/zynq_fsbl/zynq_fsbl_bsp
app_src_dir: /home/tartanauv/Xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_apps/zynq_fsbl
template: zynq_fsbl
