domain_path: /home/tartanauv/TAUV-Acoustics/hdl/projects/som_platform/export/som_platform/sw/standalone_ps7_cortexa9_0
app_src_dir: /home/tartanauv/Xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_apps/empty_application
template: empty_application
