# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/AGC_test_constraints.xdc

# Block Designs: bd/AGC/AGC.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AGC || ORIG_REF_NAME==AGC} -quiet] -quiet

# IP: bd/AGC/ip/AGC_LTC2315_Driver_Wrapp_0_0/AGC_LTC2315_Driver_Wrapp_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AGC_LTC2315_Driver_Wrapp_0_0 || ORIG_REF_NAME==AGC_LTC2315_Driver_Wrapp_0_0} -quiet] -quiet

# IP: bd/AGC/ip/AGC_clk_wiz_0_0/AGC_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AGC_clk_wiz_0_0 || ORIG_REF_NAME==AGC_clk_wiz_0_0} -quiet] -quiet

# IP: bd/AGC/ip/AGC_xlconstant_0_0/AGC_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AGC_xlconstant_0_0 || ORIG_REF_NAME==AGC_xlconstant_0_0} -quiet] -quiet

# IP: bd/AGC/ip/AGC_proc_sys_reset_0_0/AGC_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AGC_proc_sys_reset_0_0 || ORIG_REF_NAME==AGC_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/AGC/ip/AGC_processing_system7_0_0/AGC_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AGC_processing_system7_0_0 || ORIG_REF_NAME==AGC_processing_system7_0_0} -quiet] -quiet

# XDC: c:/Dev/TAUV-Acoustics/hdl/acoustics-v2-zybo/acoustics-v2-zybo.gen/sources_1/bd/AGC/AGC_ooc.xdc
