# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Dev/TAUV-Acoustics/hdl/acoustics-v2-zybo/acoustics-v2-zybo.srcs/sources_1/bd/AGC/ip/AGC_clk_wiz_0_0/AGC_clk_wiz_0_0.xci
# IP: The module: 'AGC_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Dev/TAUV-Acoustics/hdl/acoustics-v2-zybo/acoustics-v2-zybo.gen/sources_1/bd/AGC/ip/AGC_clk_wiz_0_0/AGC_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'AGC_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Dev/TAUV-Acoustics/hdl/acoustics-v2-zybo/acoustics-v2-zybo.gen/sources_1/bd/AGC/ip/AGC_clk_wiz_0_0/AGC_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'AGC_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Dev/TAUV-Acoustics/hdl/acoustics-v2-zybo/acoustics-v2-zybo.gen/sources_1/bd/AGC/ip/AGC_clk_wiz_0_0/AGC_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AGC_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Dev/TAUV-Acoustics/hdl/acoustics-v2-zybo/acoustics-v2-zybo.srcs/sources_1/bd/AGC/ip/AGC_clk_wiz_0_0/AGC_clk_wiz_0_0.xci
# IP: The module: 'AGC_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Dev/TAUV-Acoustics/hdl/acoustics-v2-zybo/acoustics-v2-zybo.gen/sources_1/bd/AGC/ip/AGC_clk_wiz_0_0/AGC_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'AGC_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Dev/TAUV-Acoustics/hdl/acoustics-v2-zybo/acoustics-v2-zybo.gen/sources_1/bd/AGC/ip/AGC_clk_wiz_0_0/AGC_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'AGC_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Dev/TAUV-Acoustics/hdl/acoustics-v2-zybo/acoustics-v2-zybo.gen/sources_1/bd/AGC/ip/AGC_clk_wiz_0_0/AGC_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AGC_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
